openapi: 3.0.0
info:
  version: 1.0.0
  title: Where's My Item? Item Service API
  description: Perform CRUD actions for items

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /residence:
    post:
      summary: Create a new residence for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nickname
              properties:
                nickname:
                  type: string
                streetAddress:
                  type: string
                city:
                  type: string
                state:
                  type: string
                country:
                  type: string
                zipCode:
                  type: string
                buildingName:
                  type: string
      responses:
        '201':
          description: Successfully created the residence

  /item:
    post:
      summary: Create a new item for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                categoryId:
                  type: string
                displayPictureUrl:
                  type: string
                notes:
                  type: string
      responses:
        '201':
          description: Successfully created the item