database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  db_name: wmi
  schema: development
jwt_key: a-jwt-secret-key
access_token_expiration_in_minutes: 180
refresh_token_expiration_in_minutes: 44640